
spring:
  application:
    name: cat-service-persistence
  data:
    mongodb:
      uri: mongodb://localhost:27017/cat-service
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: diplomadodhv2@gmail.com
    password: Password1,.-

    properties:
      mail:
        debug: false
        smtp:
          auth: true
          starttls:
            enable: true
